### ISSUE TITLE
[BUG] category search

### ISSUE THREAD

**Issue by arnaudvedy** [cityofsandiego/seaboard#126]
Search based on category leads to empty datasets page.
Example - http://data.sandiego.gov/datasets/?category=culture-and-recreation
![screen shot 2017-02-24 at 2 51 40 pm](https://cloud.githubusercontent.com/assets/22329288/23324119/d474f2d6-faa0-11e6-8bf0-ecec714c1f6f.png)
Replacing `category` with `topic` in the url solves the issue.

**Comment by andrell81** [comment]
I can't duplicate this issue
